SEED: 1113

DATA:
  PARTITION: 3 # 3: train valid test , 2: train test
  FILE_NAME: 'win_set.xlsx'
  DATA_PATH: 'res'
  X_COLS: ['rain', 'wind', 'humidity', 'pressure', 'snow', 'cloud', 'visibility',
           'Vertical', 'Horizontal', 'Module', 'Outdoor',
           'rain_t1', 'wind_t1', 'humidity_t1', 'pressure_t1', 'snow_t1', 'cloud_t1', 'visibility_t1']
  Y_TARGET: ['Vertical_t1', 'Horizontal_t1', 'Module_t1', 'Outdoor_t1']

  ## No Window
  # ['rain', 'wind', 'humidity', 'pressure', 'snow', 'cloud', 'visibility']
  # ['Vertical', 'Horizontal', 'Module', 'Outdoor']
  # ['total']

  ## Window Columns
  # ['rain', 'wind', 'humidity', 'pressure', 'snow', 'cloud', 'visibility', 'total', 'rain_t1', 'wind_t1', 'humidity_t1', 'pressure_t1', 'snow_t1', 'cloud_t1', 'visibility_t1']
  # ['Vertical', 'Horizontal', 'Module', 'Outdoor',  'total', 'Vertical_t1', 'Horizontal_t1', 'Module_t1', 'Outdoor_t1']
  # ['total_t1']

  PRESET: ''

MODEL:
  NAME: 'LSTM'
  CRITERIA: 'MSELoss'
  OPTIMIZER: 'Adam'
  LR: 0.0001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  N_CLASSES: 1 # class 개수
  CHECKPOINT: null

MODEL_PARAM:
#  HIDDEN_DIM:
#  INPUT_DIM: 7
#  OUTPUT_DIM: 1
  LAYERS: 4

TRAIN:
  BATCH_SIZE: 16
  EPOCHS: 1000
  EARLYSTOP_PATIENT: 20
  MODEL_SAVE_PATH: 'ckpt'
  LOGGING_SEP: '|'
  LOGGING_SAVE_PATH: './log.txt'
  VALID_SPLIT_SIZE: 0.2
VALID:
  BATCH_SIZE: 16
TEST:
  BATCH_SIZE: 16

ENSEMBLE:
  MODEL_LIST_DIR: 'ensemble'
  N_CLASSES: 3 # class 개수
  BATCH_SIZE: 1


# Default
#  OPTIMIZER: 'SAM'
#  LR: 0.01
#  MOMENTUM: 0.9
#  WEIGHT_DECAY: 0.000001