SEED: 555

DATA:
  PAIR : ['contradiction', 'entailment', 'neutral']
  IMAGE_SIZE: 224
MODEL:
  NAME: 'Huffon/klue-roberta-base-nli'
  CRITERIA: CrossEntropy
  OPTIMIZER: AdamW
  LR: 0.001
  WEIGHT_DECAY: 0.01
  CHECKPOINT: null # null == None, 불러올 모델
  N_CLASSES: 2 # class 개수
TRAIN:
  LR: 0.001
  BATCH_SIZE: 8
  SEED: 2022
  EPOCHS: 100
  EARLYSTOP_PATIENT: 10
  DEVICE: null
  MODEL_SAVE_PATH: './ckpt/template/best.pth'
  LOGGING_SEP: '|'
  LOGGING_SAVE_PATH: './log.txt'
VALID:
  BATCH_SIZE: 8
TEST:
  BATCH_SIZE: 8